---
name: check_load_procs
pack: e_nagios
description: Check running procs on host when load is high
enabled: false
trigger:
  type: e_nagios.service_state_change
criteria:
  trigger.service:
    pattern: "(.*)_check_loadavg"
    type: matchregex
  trigger.state_type:
    pattern: HARD
    type: matchregex
action:
  ref: e_nagios.check_procs
  parameters:
    hosts: "{{trigger.host}}"
    cmd: state R
