---
name: check_proc
pack: e_nagios
description: Check process state on host
enabled: false
trigger:
  type: nagios.service_state_change
criteria:
  service:
    pattern: "(.*)_check_(.*)_process"
    type: matchregex
  state_type:
    pattern: HARD
    type: matchregex
action:
  ref: e_nagios.check_pgrep
  parameters:
    hosts: "{{trigger.host}}"
    cmd: "{{trigger.service}} 1 10"
